### ISSUE TITLE
Custom sky (OptiFine) doesn't work in 1.0.3 (1.8.9)

### ISSUE THREAD

**Issue by ghost** [chylex/Resource-Pack-Organizer#28] opened 2020-09-14 19:17 UTC
The title says everything. Does it work in newer versions? Is it because I'm using it on 1.8.9? Is it McPatcher's fault?

**Comment by chylex** [comment] 2020-09-14 19:26
Duplicate of #7.

**Closed as completed by chylex** 2020-09-14 19:26 UTC
