### ISSUE TITLE
Custom skys not working

### ISSUE THREAD

**Issue by usernameisntused** [chylex/Resource-Pack-Organizer#27] opened 2020-09-06 08:08 UTC
When I try to use a custom sky with the mod not installed it works but when I try with it installed it doesn't work.

**Comment by usernameisntused** [comment] 2020-09-06 08:25
might be because I'm using 1.8.9

**Comment by chylex** [comment] 2020-09-06 09:48
Duplicate of #7

**Closed by chylex** 2020-09-06 09:48 UTC
