### ISSUE TITLE
1.12.2 messes with your custom sky.

### ISSUE THREAD

**Issue by Jukaido** [chylex/Resource-Pack-Organizer#32] opened 2021-02-22 07:59 UTC
I'm not sure if this happens with other versions, but if you use this mod on 1.12.2 the custom sky from your resource pack is gone. I've tried everything to get it to work even have been in contacted with people at optifine but the mod was the issue. When I removed the mod from my mods folder my custom sky worked fine.

**Comment by chylex** [comment] 2021-02-22 14:45
Duplicate of #7

**Closed as completed by chylex** 2021-02-22 14:45 UTC
