### ISSUE TITLE
The Sky Not Showing

### ISSUE THREAD

**Issue by NiscoroGaming** [chylex/Resource-Pack-Organizer#33] opened 2021-07-22 15:14 UTC
In The Newest 1.8.9 Resource Pack Organizer Mod, If You Have A Custom Sky In A Resource Pack With The Resource Pack On. It Doesn't Show And If I Go To An Older Version It Shows But It Doesn't Let Me Scroll Down In The Resource Packs Menu.

**Comment by chylex** [comment] 2021-07-22 19:33
Duplicate of #7.

**Closed as completed by chylex** 2021-07-22 19:33 UTC
