### ISSUE TITLE
Custom Skies not working

### ISSUE THREAD

**Issue by xoxoe** [chylex/Resource-Pack-Organizer#29] opened 2020-09-28 13:11 UTC
When i install this mod on 1.8.9 forge with several other mods my custom skies from texture packs dont work. The sky just appears white.

I am 100% certain that it is this mod causing the problem.

**Comment by chylex** [comment] 2020-09-28 14:40
Duplicate of #7.

**Closed as completed by chylex** 2020-09-28 14:40 UTC
